import { jsPDF } from 'jspdf'

export default function generatePDF(studentData, results) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Title
  doc.setFontSize(18)
  doc.text('DOrSU College Program Recommender', pageWidth / 2, y, { align: 'center' })
  y += 10
  doc.setFontSize(12)
  doc.text('Personalized Program Recommendation Report', pageWidth / 2, y, { align: 'center' })
  y += 8
  doc.setFontSize(10)
  doc.text(`Generated for: ${studentData.name || 'Student'}`, 20, y)
  y += 6
  doc.text(`SHS Strand: ${studentData.strand || 'N/A'}`, 20, y)
  y += 6
  if (studentData.gwa) doc.text(`GWA: ${studentData.gwa}`, 20, y)

  y += 12

  // Results table
  doc.setFontSize(14)
  doc.text('Top 10 Recommended Programs', 20, y)
  y += 8

  if (!results || results.length === 0) {
    doc.setFontSize(11)
    doc.text('No recommendations available.', 20, y)
  } else {
    // Table header
    doc.setFontSize(9)
    doc.setFont(undefined, 'bold')
    const headers = ['Rank', 'Program', 'Score', 'Admission']
    const colWidths = [12, 80, 20, 30]
    let x = 20
    headers.forEach((h, i) => {
      doc.text(h, x, y)
      x += colWidths[i]
    })
    doc.setFont(undefined, 'normal')
    y += 5

    // Table rows
    doc.setFontSize(8)
    results.forEach(r => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      x = 20
      doc.text(`${r.rank}`, x, y); x += colWidths[0]
      doc.text(r.program.name.substring(0, 40), x, y); x += colWidths[1]
      doc.text(`${r.totalScore}%`, x, y); x += colWidths[2]
      doc.text(r.admission.label, x, y)
      y += 5
    })

    y += 8

    // Score breakdown for top 3
    doc.setFontSize(12)
    doc.text('Score Breakdown (Top 3)', 20, y)
    y += 7

    const top3 = results.slice(0, 3)
    top3.forEach(r => {
      if (y > 260) { doc.addPage(); y = 20 }
      doc.setFontSize(10)
      doc.setFont(undefined, 'bold')
      doc.text(`#${r.rank}: ${r.program.name}`, 20, y)
      y += 5
      doc.setFont(undefined, 'normal')
      doc.setFontSize(9)
      doc.text(`Academic: ${r.breakdown.academic}%  |  SUAST: ${r.breakdown.suast}%  |  Personal Fit: ${r.breakdown.personalFit}%`, 25, y)
      y += 5
      doc.text(`Overall Score: ${r.totalScore}%  |  Admission Chance: ${r.admission.label} (${r.admission.value})`, 25, y)
      y += 8
    })
  }

  // Footer
  y = Math.max(y + 10, 280)
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by DCPR — DOrSU College Program Recommender (Prototype)', pageWidth / 2, y, { align: 'center' })

  doc.save('DCPR_Recommendation_Report.pdf')
}
